import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:logger/logger.dart';
import 'package:moor_flutter/moor_flutter.dart';
import 'package:projyproject/repository/database.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse3Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine1Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine2Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine3Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine4Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine5Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine6Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedLine7Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedProjyWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedRegisterWidget.dart';
import 'package:projyproject/view_model/bloc.dart';
import 'package:provider/provider.dart';

/* Component registerscreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterscreenWidget extends StatefulWidget {
  @override
  State<GeneratedRegisterscreenWidget> createState() =>
      _GeneratedRegisterscreenWidgetState();
}

class _GeneratedRegisterscreenWidgetState
    extends State<GeneratedRegisterscreenWidget> {
  Bloc get bloc => Provider.of<Bloc>(context, listen: false);

  final _nameTextController = TextEditingController();

  final _emailTextController = TextEditingController();

  final _passwordTextController = TextEditingController();

  final _usernameTextController = TextEditingController();

  final _genderTextController = TextEditingController();

  final _birthdayTextController = TextEditingController();

  final _locationTextController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    Logger logger = Logger();

    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1059.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 420.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 102, 59, 223),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth - -92.0;
                                final double scaleX =
                                    width <= 0 ? 0 : (width / 512.0);

                                final double height =
                                    constraints.maxHeight - -337.0;
                                final double scaleY =
                                    height <= 0 ? 0 : (height / 1233.0);

                                final Widget child =
                                    GeneratedRectangle1Widget();
                                return Stack(children: [
                                  Transform(
                                    transform: Matrix4(
                                        scaleX,
                                        0,
                                        0,
                                        0,
                                        0,
                                        scaleY,
                                        0,
                                        0,
                                        0,
                                        0,
                                        1,
                                        0,
                                        -45.0 * scaleX,
                                        -174.0 * scaleY,
                                        0,
                                        1),
                                    alignment: Alignment.topLeft,
                                    child: SizedBox.expand(child: child),
                                  )
                                ]);
                              }),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 448.2312927246094,
                              height: 576.7589111328125,
                              child: TransformHelper.translate(
                                  x: -81.48,
                                  y: 200.74,
                                  z: 0,
                                  child: GeneratedRectangle4Widget()),
                            ),
                            Positioned(
                              left: -45.0,
                              top: -113.0,
                              right: null,
                              bottom: null,
                              width: 217.0,
                              height: 226.0,
                              child: GeneratedEllipse1Widget(),
                            ),
                            Positioned(
                              left: 130.0,
                              top: -59.0,
                              right: null,
                              bottom: null,
                              width: 197.0,
                              height: 221.0,
                              child: GeneratedEllipse3Widget(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: -66.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 179.0,
                              child: GeneratedEllipse5Widget(),
                            ),
                            Positioned(
                              left: 264.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 201.0,
                              child: GeneratedEllipse4Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 229.0,
                              height: 70.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 365.00,
                                  z: 0,
                                  child: GeneratedEllipse6Widget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 369.0000305175781,
                              height: 610.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 28.00,
                                  z: 0,
                                  child: GeneratedRectangle3Widget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 208.46665954589844,
                              height: 47.0,
                              child: TransformHelper.translate(
                                  x: 3.23,
                                  y: 367.50,
                                  z: 0,
                                  child: FloatingActionButton(
                                    backgroundColor: Colors.transparent,
                                    elevation: 0,
                                    onPressed: () async {
                                      if (_emailTextController.text == "" ||
                                          _usernameTextController.text == "" ||
                                          _passwordTextController.text == "" ||
                                          _nameTextController.text == "") {
                                        Widget okButton = TextButton(
                                          child: Text("OK"),
                                          onPressed: () {
                                            return Navigator.of(context,
                                                    rootNavigator: true)
                                                .pop(); // dismisses only the dialog and returns nothing
                                          },
                                        );
                                        AlertDialog alert = AlertDialog(
                                          title: Text("Warning!"),
                                          content: Text(
                                              "Mandatory fields cannot be empty!"),
                                          actions: [
                                            okButton,
                                          ],
                                        );
                                        showDialog(
                                          context: context,
                                          builder: (BuildContext context) {
                                            return alert;
                                          },
                                        );
                                      } else {
                                        final user = LocalUsersCompanion.insert(
                                            id: '',
                                            username:
                                                _usernameTextController.text,
                                            password:
                                                _passwordTextController.text,
                                            firstname: _nameTextController.text
                                                .split(' ')[0],
                                            lastname: _nameTextController.text
                                                .split(' ')[1],
                                            gender: _genderTextController.text,
                                            email: _emailTextController.text,
                                            location:
                                                _locationTextController.text,
                                            birthday:
                                                _birthdayTextController.text);

                                        bloc.addEntry(user).then((value) {
                                          logger.d("Register User: " +
                                              value.toString());

                                          if (!value) {
                                            Widget okButton = TextButton(
                                              child: Text("OK"),
                                              onPressed: () {
                                                //Navigator.pop(context);
                                                return Navigator.of(context,
                                                        rootNavigator: true)
                                                    .pop();
                                              },
                                            );
                                            AlertDialog alert = AlertDialog(
                                              title: Text("Warning!"),
                                              content: Text(
                                                  "No internet connection!"),
                                              actions: [
                                                okButton,
                                              ],
                                            );
                                            showDialog(
                                              context: context,
                                              builder: (BuildContext context) {
                                                return alert;
                                              },
                                            );
                                          } else {
                                            Navigator.of(context)
                                                .pushNamed('/intro');
                                          }
                                        });
                                      }
                                    },
                                    child: Align(
                                      alignment: Alignment.center,
                                      child: Text(
                                        '''Register''',
                                        overflow: TextOverflow.visible,
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          height: 1,
                                          fontSize: 45,
                                          fontFamily: 'Work Sans',
                                          fontWeight: FontWeight.w700,
                                          color: Color.fromARGB(
                                              255, 255, 255, 255),

                                          /* letterSpacing: -1.0757393646240234, */
                                        ),
                                      ),
                                    ),
                                  )),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: 292.00,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _locationTextController,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Location',
                                        hintText: 'Enter Location',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: 214.50,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _birthdayTextController,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Birthday',
                                        hintText: 'Enter Birthday',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: 136.00,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _genderTextController,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Gender',
                                        hintText: 'Enter Gender',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: 52.00,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _passwordTextController,
                                      obscureText: true,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Password*',
                                        hintText: 'Enter Password',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: -38.50,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _emailTextController,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Email*',
                                        hintText: 'Enter Email',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: -134.50,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _usernameTextController,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Username*',
                                        hintText: 'Enter Username',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 350,
                              height: 100,
                              child: TransformHelper.translate(
                                x: -5,
                                y: -221.00,
                                z: 0,
                                child: Padding(
                                  padding: EdgeInsets.all(15),
                                  child: SizedBox(
                                    child: TextFormField(
                                      controller: _nameTextController,
                                      textAlign: TextAlign.center,
                                      decoration: InputDecoration(
                                        border: OutlineInputBorder(),
                                        labelText: 'Name*',
                                        hintText: 'Enter First and Last Name',
                                        enabledBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Color.fromARGB(
                                                    255, 135, 134, 231),
                                                width: 1.5),
                                            borderRadius:
                                                BorderRadius.circular(25.0)),
                                        focusedBorder: OutlineInputBorder(
                                          borderSide: const BorderSide(
                                              color: Color.fromARGB(
                                                  255, 135, 134, 231),
                                              width: 2.0),
                                          borderRadius:
                                              BorderRadius.circular(25.0),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 202.0,
                              height: 88.6424560546875,
                              child: TransformHelper.translate(
                                  x: 69.00,
                                  y: -324.68,
                                  z: 0,
                                  child: GeneratedProjyWidget()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
