import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:intl/intl.dart';
import 'package:logger/logger.dart';
import 'package:projyproject/repository/database.dart';
import 'package:projyproject/shared/menu_drawer.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedProjyWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedEllipse12Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup14Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup15Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup16Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup17Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup19Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup20Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedGroup21Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedRectangle5Widget1.dart';
import 'package:projyproject/ui_screens/projyapp/generatedpostprojectwidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:provider/provider.dart';

import '../../../view_model/bloc.dart';
import '../../helpers/svg/svg.dart';

/* Component postProject
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPostProjectWidget extends StatefulWidget {
  @override
  State<GeneratedPostProjectWidget> createState() =>
      _GeneratedPostProjectWidgetState();
}

class _GeneratedPostProjectWidgetState
    extends State<GeneratedPostProjectWidget> {
  Bloc get bloc => Provider.of<Bloc>(context, listen: false);

  final _titleTextController = TextEditingController();
  final _descriptionTextController = TextEditingController();

  var logger = Logger();

  @override
  Widget build(BuildContext context) {
    var scaffoldKey = GlobalKey<ScaffoldState>();
    return Scaffold(
        drawer: ClipRRect(
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(1000),
              bottomRight: Radius.circular(10)),
          child: MenuDrawer(),
        ),
        appBar: AppBar(
            key: scaffoldKey,
            leading: Builder(
              builder: (context) => IconButton(
                icon: Icon(Icons.menu_rounded),
                iconSize: 40,
                onPressed: () => Scaffold.of(context).openDrawer(),
              ),
            ),
            flexibleSpace: Container(
              decoration: new BoxDecoration(
                gradient: new LinearGradient(
                    colors: [
                      Color.fromARGB(255, 102, 59, 223),
                      Color.fromARGB(255, 135, 134, 231),
                    ],
                    begin: const FractionalOffset(0.0, 0.0),
                    end: const FractionalOffset(1.0, 0.0),
                    stops: [0.0, 1.0],
                    tileMode: TileMode.clamp),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                    ),
                    Positioned(
                      left: null,
                      top: -110,
                      right: -68.0,
                      bottom: null,
                      width: 192.0,
                      height: 207.0,
                      child: GeneratedEllipse8Widget(),
                    ),
                    Positioned(
                      left: null,
                      top: 40,
                      right: -4.8552703857421875,
                      bottom: null,
                      width: 96.85527038574219,
                      height: 44.0,
                      child: GeneratedProjyWidget(),
                    ),
                  ]),
            )),
        body: Material(
            child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 896.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 414.0,
                          height: 896.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 135, 134, 231),
                                  ),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 451.0,
                                  right: null,
                                  bottom: null,
                                  width: 63.0,
                                  height: 88.54545593261719,
                                  child: GeneratedGroup20Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: -14.0,
                                  right: -19.0,
                                  bottom: null,
                                  width: 56.0,
                                  height: 99.54545593261719,
                                  child: GeneratedGroup21Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: null,
                                  right: -25.0,
                                  bottom: 16.0,
                                  width: 119.0,
                                  height: 139.0,
                                  child: GeneratedGroup19Widget(),
                                ),
                                Positioned(
                                  left: 30.0,
                                  top: 20.0,
                                  right: 30.0,
                                  bottom: null,
                                  width: null,
                                  height: 40.0,
                                  child: SizedBox.expand(
                                      child: Container(
                                    width: null,
                                    height: 40.0,
                                    child: SizedBox(
                                      child: TextField(
                                        textAlign: TextAlign.center,
                                        controller: _titleTextController,
                                        decoration: InputDecoration(
                                          border: OutlineInputBorder(),
                                          labelText: 'Title',
                                          hintText: 'Enter Title',
                                          filled: true,
                                          fillColor: Colors.white,
                                          enabledBorder: OutlineInputBorder(
                                              borderSide: const BorderSide(
                                                  color: Colors.white,
                                                  width: 1),
                                              borderRadius:
                                                  BorderRadius.circular(25.0)),
                                          focusedBorder: OutlineInputBorder(
                                            borderSide: const BorderSide(
                                                color: Colors.white,
                                                width: 2.0),
                                            borderRadius:
                                                BorderRadius.circular(25.0),
                                          ),
                                        ),
                                      ),
                                    ),
                                  )),
                                ),
                                Positioned(
                                  left: 16.0,
                                  top: 78.0,
                                  right: 16.0,
                                  bottom: null,
                                  width: null,
                                  height: 500.2474060058594,
                                  child: Container(
                                    width: 382.0,
                                    height: 366.2474060058594,
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        overflow: Overflow.visible,
                                        children: [
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: 0.0,
                                            bottom: null,
                                            width: null,
                                            height: 366.2474060058594,
                                            child: LayoutBuilder(builder:
                                                (BuildContext context,
                                                    BoxConstraints
                                                        constraints) {
                                              final double width =
                                                  constraints.maxWidth - 0.0;
                                              final double scaleX = width <= 0
                                                  ? 0
                                                  : (width / 382.0);

                                              final Widget child =
                                                  GeneratedRectangle6Widget1();
                                              return Stack(children: [
                                                Transform(
                                                  transform: Matrix4(
                                                      scaleX,
                                                      0,
                                                      0,
                                                      0,
                                                      0,
                                                      1,
                                                      0,
                                                      0,
                                                      0,
                                                      0,
                                                      1,
                                                      0,
                                                      2.842170943040401e-14 *
                                                          scaleX,
                                                      0.0,
                                                      0,
                                                      1),
                                                  alignment: Alignment.topLeft,
                                                  child: SizedBox.expand(
                                                      child: child),
                                                )
                                              ]);
                                            }),
                                          ),
                                          Positioned(
                                              left: 11.057889938354492,
                                              top: 0.000005901189069845714,
                                              right: 12.063173294067383,
                                              bottom: null,
                                              width: null,
                                              height: 1000.2474060058594,
                                              child: Container(
                                                width: 358.8789367675781,
                                                height: 366.2474060058594,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          49.226802825927734),
                                                ),
                                                child: SizedBox(
                                                    height: 500,
                                                    child: Container(
                                                      width: null,
                                                      height: 100.0,
                                                      child: SizedBox(
                                                        child: TextField(
                                                          minLines: 1,
                                                          maxLines:
                                                              17, // allow user to enter 5 line in textfield
                                                          keyboardType:
                                                              TextInputType
                                                                  .multiline,
                                                          textAlign:
                                                              TextAlign.center,
                                                          controller:
                                                              _descriptionTextController,
                                                          decoration:
                                                              InputDecoration(
                                                            border:
                                                                OutlineInputBorder(),
                                                            labelText:
                                                                'Description',
                                                            hintText:
                                                                'Enter Description',
                                                            filled: true,
                                                            fillColor:
                                                                Colors.white,
                                                            enabledBorder: OutlineInputBorder(
                                                                borderSide:
                                                                    const BorderSide(
                                                                        color: Colors
                                                                            .white,
                                                                        width:
                                                                            1),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0)),
                                                            focusedBorder:
                                                                OutlineInputBorder(
                                                              borderSide:
                                                                  const BorderSide(
                                                                      color: Colors
                                                                          .white,
                                                                      width:
                                                                          2.0),
                                                              borderRadius:
                                                                  BorderRadius
                                                                      .circular(
                                                                          25.0),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    )),
                                              ))
                                        ]),
                                  ),
                                ),
                                Positioned(
                                  left: null,
                                  top: 552.0,
                                  right: null,
                                  bottom: null,
                                  width: 388.0,
                                  height: 186.0,
                                  child: GeneratedGroup15Widget(),
                                ),
                                Positioned(
                                  left: null,
                                  top: 457.0,
                                  right: null,
                                  bottom: null,
                                  width: 255.0,
                                  height: 75.0,
                                  child: TransformHelper.translate(
                                      x: -1.50,
                                      y: 0.00,
                                      z: 0,
                                      child: GeneratedGroup16Widget()),
                                ),
                                Positioned(
                                  left: null,
                                  top: 745.0,
                                  right: null,
                                  bottom: null,
                                  width: 255.0,
                                  height: 75.0,
                                  child: TransformHelper.translate(
                                      x: -1.50,
                                      y: 0.00,
                                      z: 0,
                                      child: Container(
                                        width: 255.0,
                                        height: 75.0,
                                        child: Stack(
                                            fit: StackFit.expand,
                                            alignment: Alignment.center,
                                            overflow: Overflow.visible,
                                            children: [
                                              Positioned(
                                                left: null,
                                                top: 0.0,
                                                right: null,
                                                bottom: null,
                                                width: 255.0,
                                                height: 75.0,
                                                child:
                                                    GeneratedEllipse12Widget1(),
                                              ),
                                              Positioned(
                                                  left: null,
                                                  top: 20.0,
                                                  right: null,
                                                  bottom: null,
                                                  width: 249.25807189941406,
                                                  height: 37.0,
                                                  child:
                                                      TransformHelper.translate(
                                                    x: 2.13,
                                                    y: 0.00,
                                                    z: 0,
                                                    child: FloatingActionButton(
                                                        backgroundColor:
                                                            Colors.transparent,
                                                        elevation: 0,
                                                        onPressed: () {
                                                          if (_titleTextController
                                                                      .text ==
                                                                  "" ||
                                                              _descriptionTextController
                                                                      .text ==
                                                                  "") {
                                                            Widget okButton =
                                                                TextButton(
                                                              child: Text("OK"),
                                                              onPressed: () {
                                                                return Navigator.of(
                                                                        context,
                                                                        rootNavigator:
                                                                            true)
                                                                    .pop(); // dismisses only the dialog and returns nothing
                                                              },
                                                            );
                                                            AlertDialog alert =
                                                                AlertDialog(
                                                              title: Text(
                                                                  "Warning!"),
                                                              content: Text(
                                                                  "No empty fields allowed!"),
                                                              actions: [
                                                                okButton,
                                                              ],
                                                            );
                                                            showDialog(
                                                              context: context,
                                                              builder:
                                                                  (BuildContext
                                                                      context) {
                                                                return alert;
                                                              },
                                                            );
                                                          } else {
                                                            bloc
                                                                .getLoggedUser()
                                                                .then((value) {
                                                              DateTime now =
                                                                  DateTime
                                                                      .now();
                                                              String
                                                                  formattedDate =
                                                                  DateFormat(
                                                                          'kk:mm:ss EEE d MMM')
                                                                      .format(
                                                                          now);

                                                              final post = LocalPostsCompanion.insert(
                                                                  id: '',
                                                                  description:
                                                                      _descriptionTextController
                                                                          .text,
                                                                  title:
                                                                      _titleTextController
                                                                          .text,
                                                                  date: formattedDate
                                                                      .toString(),
                                                                  userid:
                                                                      value.id);

                                                              bloc
                                                                  .addPostEntry(
                                                                      post)
                                                                  .then(
                                                                      (value) {
                                                                logger.d(
                                                                    "Add Post: " +
                                                                        value
                                                                            .toString());

                                                                if (!value) {
                                                                  Widget
                                                                      okButton =
                                                                      TextButton(
                                                                    child: Text(
                                                                        "OK"),
                                                                    onPressed:
                                                                        () {
                                                                      //Navigator.pop(context);
                                                                      return Navigator.of(
                                                                              context,
                                                                              rootNavigator: true)
                                                                          .pop();
                                                                    },
                                                                  );
                                                                  AlertDialog
                                                                      alert =
                                                                      AlertDialog(
                                                                    title: Text(
                                                                        "Warning!"),
                                                                    content: Text(
                                                                        "No internet connection!"),
                                                                    actions: [
                                                                      okButton,
                                                                    ],
                                                                  );
                                                                  showDialog(
                                                                    context:
                                                                        context,
                                                                    builder:
                                                                        (BuildContext
                                                                            context) {
                                                                      return alert;
                                                                    },
                                                                  );
                                                                } else {
                                                                  Fluttertoast.showToast(
                                                                      msg:
                                                                          "Successfully posted!",
                                                                      toastLength:
                                                                          Toast
                                                                              .LENGTH_SHORT,
                                                                      gravity: ToastGravity
                                                                          .CENTER,
                                                                      timeInSecForIosWeb:
                                                                          1,
                                                                      backgroundColor:
                                                                          Colors
                                                                              .green,
                                                                      textColor:
                                                                          Colors
                                                                              .white,
                                                                      fontSize:
                                                                          16.0);
                                                                }
                                                              });
                                                            });
                                                          }
                                                        },
                                                        child: Align(
                                                          alignment:
                                                              Alignment.center,
                                                          child: Text(
                                                            '''Post Project''',
                                                            overflow:
                                                                TextOverflow
                                                                    .visible,
                                                            textAlign: TextAlign
                                                                .center,
                                                            style: TextStyle(
                                                              height:
                                                                  1.1718749898575689,
                                                              fontSize:
                                                                  35.26056671142578,
                                                              fontFamily:
                                                                  'Work Sans',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w700,
                                                              color: Color
                                                                  .fromARGB(
                                                                      255,
                                                                      255,
                                                                      255,
                                                                      255),

                                                              /* letterSpacing: -0.7052113342285157, */
                                                            ),
                                                          ),
                                                        )),
                                                  ))
                                            ]),
                                      )),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
        )));
  }
}
