import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:intl/intl.dart';
import 'package:logger/logger.dart';
import 'package:projyproject/repository/database.dart';

import 'package:projyproject/shared/menu_drawer.dart';
import 'package:projyproject/ui_screens/helpers/transform/transform.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedhomescreenwidget/generated/GeneratedProjyWidget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse3Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedregisterscreenwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedEllipse10Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup13Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup7Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup8Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedGroup9Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:projyproject/ui_screens/projyapp/generatedupdateprofilescreenwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:projyproject/view_model/bloc.dart';
import 'package:provider/provider.dart';

import '../generatedregisterscreenwidget/generated/GeneratedRectangle1Widget.dart';

/* Component updateprofilescreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUpdateprofilescreenWidget extends StatefulWidget {
  @override
  State<GeneratedUpdateprofilescreenWidget> createState() =>
      _GeneratedUpdateprofilescreenWidgetState();
}

class _GeneratedUpdateprofilescreenWidgetState
    extends State<GeneratedUpdateprofilescreenWidget> {
  Bloc get bloc => Provider.of<Bloc>(context, listen: false);

  final _firstnameTextController = TextEditingController();

  final _lastnameTextController = TextEditingController();

  final _emailTextController = TextEditingController();

  final _passwordTextController = TextEditingController();

  final _usernameTextController = TextEditingController();

  final _genderTextController = TextEditingController();

  final _birthdayTextController = TextEditingController();

  final _locationTextController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    Logger logger = Logger();

    bloc.getLoggedUser().then((value) {
      _firstnameTextController.text = value.firstname;
      _lastnameTextController.text = value.lastname;
      _emailTextController.text = value.email;
      _genderTextController.text = value.gender.toString();
      logger.d(value.gender);

      _passwordTextController.text = value.password;
      _usernameTextController.text = value.username;
      _locationTextController.text = value.location;
      _birthdayTextController.text = value.birthday;
    });

    var scaffoldKey = GlobalKey<ScaffoldState>();
    return Scaffold(
        drawer: ClipRRect(
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(1000),
              bottomRight: Radius.circular(10)),
          child: MenuDrawer(),
        ),
        appBar: AppBar(
            key: scaffoldKey,
            leading: Builder(
              builder: (context) => IconButton(
                icon: Icon(Icons.menu_rounded),
                iconSize: 40,
                onPressed: () => Scaffold.of(context).openDrawer(),
              ),
            ),
            flexibleSpace: Container(
              decoration: new BoxDecoration(
                gradient: new LinearGradient(
                    colors: [
                      Color.fromARGB(255, 102, 59, 223),
                      Color.fromARGB(255, 135, 134, 231),
                    ],
                    begin: const FractionalOffset(0.0, 0.0),
                    end: const FractionalOffset(1.0, 0.0),
                    stops: [0.0, 1.0],
                    tileMode: TileMode.clamp),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                    ),
                    Positioned(
                      left: null,
                      top: -110,
                      right: -68.0,
                      bottom: null,
                      width: 192.0,
                      height: 207.0,
                      child: GeneratedEllipse8Widget(),
                    ),
                    Positioned(
                      left: null,
                      top: 40,
                      right: -4.8552703857421875,
                      bottom: null,
                      width: 96.85527038574219,
                      height: 44.0,
                      child: GeneratedProjyWidget(),
                    ),
                  ]),
            )),
        body: Material(
            child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 966.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                            width: 423.0,
                            height: 966.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 135, 134, 231),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 386.0,
                                    height: 612.0,
                                    child: TransformHelper.translate(
                                        x: -0.50,
                                        y: -40,
                                        z: 0,
                                        child: Container(
                                            width: 386.0,
                                            height: 612.0,
                                            child: Stack(
                                                fit: StackFit.expand,
                                                alignment: Alignment.center,
                                                overflow: Overflow.visible,
                                                children: [
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 386.0,
                                                    height: 612.0,
                                                    child:
                                                        GeneratedRectangle6Widget(),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 367.0,
                                                    height: 607.0,
                                                    child: TransformHelper
                                                        .translate(
                                                            x: -0.50,
                                                            y: -0.50,
                                                            z: 0,
                                                            child:
                                                                GeneratedRectangle5Widget()),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 350,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -5,
                                                      y: 250.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _locationTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Location',
                                                              hintText:
                                                                  'Enter Location',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 350,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -5,
                                                      y: 160.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _birthdayTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            onTap: () async {
                                                              DateTime?
                                                                  pickedDate =
                                                                  await showDatePicker(
                                                                      context:
                                                                          context,
                                                                      initialDate:
                                                                          DateTime
                                                                              .now(),
                                                                      firstDate:
                                                                          DateTime(
                                                                              2000), //DateTime.now() - not to allow to choose before today.
                                                                      lastDate:
                                                                          DateTime(
                                                                              2101));

                                                              if (pickedDate !=
                                                                  null) {
                                                                print(
                                                                    pickedDate); //pickedDate output format => 2021-03-10 00:00:00.000
                                                                String
                                                                    formattedDate =
                                                                    DateFormat(
                                                                            'yyyy-MM-dd')
                                                                        .format(
                                                                            pickedDate);
                                                                print(
                                                                    formattedDate); //formatted date output using intl package =>  2021-03-16
                                                                //you can implement different kind of Date Format here according to your requirement

                                                                setState(() {
                                                                  _birthdayTextController
                                                                          .text =
                                                                      formattedDate; //set output date to TextField value.
                                                                });
                                                              } else {
                                                                logger.d(
                                                                    "Date is not selected");
                                                              }
                                                            },
                                                            decoration:
                                                                InputDecoration(
                                                              icon: Icon(Icons
                                                                  .calendar_today),
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Birthday',
                                                              hintText:
                                                                  'Enter Birthday',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 350,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -5,
                                                      y: 70.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _genderTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Gender',
                                                              hintText:
                                                                  'female, male, other',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 350,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -5,
                                                      y: -10.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _passwordTextController,
                                                            obscureText: true,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Password*',
                                                              hintText:
                                                                  'Enter Password',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 350,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -5,
                                                      y: -90.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _emailTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Email*',
                                                              hintText:
                                                                  'user@email.com',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 350,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -5,
                                                      y: -170.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _usernameTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Username*',
                                                              hintText:
                                                                  'Enter Username',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 190,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: -90,
                                                      y: -250.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _firstnameTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'First Name*',
                                                              hintText:
                                                                  'First Name',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 190,
                                                    height: 100,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: 80,
                                                      y: -250.00,
                                                      z: 0,
                                                      child: Padding(
                                                        padding:
                                                            EdgeInsets.all(15),
                                                        child: SizedBox(
                                                          child: TextFormField(
                                                            controller:
                                                                _lastnameTextController,
                                                            textAlign: TextAlign
                                                                .center,
                                                            decoration:
                                                                InputDecoration(
                                                              border:
                                                                  OutlineInputBorder(),
                                                              labelText:
                                                                  'Last Name*',
                                                              hintText:
                                                                  'Last Name',
                                                              enabledBorder: OutlineInputBorder(
                                                                  borderSide: const BorderSide(
                                                                      color: Color.fromARGB(
                                                                          255,
                                                                          135,
                                                                          134,
                                                                          231),
                                                                      width:
                                                                          1.5),
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              25.0)),
                                                              focusedBorder:
                                                                  OutlineInputBorder(
                                                                borderSide: const BorderSide(
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            135,
                                                                            134,
                                                                            231),
                                                                    width: 2.0),
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            25.0),
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                ]))),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 261.0,
                                    height: 69.0,
                                    child: TransformHelper.translate(
                                        x: 0.00,
                                        y: 305,
                                        z: 0,
                                        child: Container(
                                          width: 261.0,
                                          height: 69.0,
                                          child: Stack(
                                              fit: StackFit.expand,
                                              alignment: Alignment.center,
                                              overflow: Overflow.visible,
                                              children: [
                                                Positioned(
                                                  left: null,
                                                  top: null,
                                                  right: null,
                                                  bottom: null,
                                                  width: 261.0,
                                                  height: 69.0,
                                                  child:
                                                      GeneratedEllipse9Widget(),
                                                ),
                                                Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 230.375,
                                                    height: 52.181819915771484,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: 1.00,
                                                      y: 0.48,
                                                      z: 0,
                                                      child:
                                                          FloatingActionButton(
                                                              backgroundColor:
                                                                  Colors
                                                                      .transparent,
                                                              elevation: 0,
                                                              onPressed:
                                                                  () async {
                                                                if (_emailTextController.text == "" ||
                                                                    _usernameTextController
                                                                            .text ==
                                                                        "" ||
                                                                    _passwordTextController
                                                                            .text ==
                                                                        "" ||
                                                                    _firstnameTextController
                                                                            .text ==
                                                                        "" ||
                                                                    _lastnameTextController
                                                                            .text ==
                                                                        "") {
                                                                  Widget
                                                                      okButton =
                                                                      TextButton(
                                                                    child: Text(
                                                                        "OK"),
                                                                    onPressed:
                                                                        () {
                                                                      return Navigator.of(
                                                                              context,
                                                                              rootNavigator: true)
                                                                          .pop(); // dismisses only the dialog and returns nothing
                                                                    },
                                                                  );
                                                                  AlertDialog
                                                                      alert =
                                                                      AlertDialog(
                                                                    title: Text(
                                                                        "Warning!"),
                                                                    content: Text(
                                                                        "Mandatory fields cannot be empty!"),
                                                                    actions: [
                                                                      okButton,
                                                                    ],
                                                                  );
                                                                  showDialog(
                                                                    context:
                                                                        context,
                                                                    builder:
                                                                        (BuildContext
                                                                            context) {
                                                                      return alert;
                                                                    },
                                                                  );
                                                                } else {
                                                                  bloc
                                                                      .getLoggedUser()
                                                                      .then(
                                                                          (value) {
                                                                    final user = UserEntry(
                                                                        id: value
                                                                            .id,
                                                                        username: _usernameTextController
                                                                            .text,
                                                                        password:
                                                                            _passwordTextController
                                                                                .text,
                                                                        firstname:
                                                                            _firstnameTextController
                                                                                .text,
                                                                        lastname:
                                                                            _lastnameTextController
                                                                                .text,
                                                                        gender: _genderTextController
                                                                            .text,
                                                                        email: _emailTextController
                                                                            .text,
                                                                        location:
                                                                            _locationTextController
                                                                                .text,
                                                                        birthday:
                                                                            _birthdayTextController.text);

                                                                    bloc.updateEntry(
                                                                        user);

                                                                    logger.d(
                                                                        "Update User: " +
                                                                            user.toString());

                                                                    if (user ==
                                                                        null) {
                                                                      Widget
                                                                          okButton =
                                                                          TextButton(
                                                                        child: Text(
                                                                            "OK"),
                                                                        onPressed:
                                                                            () {
                                                                          //Navigator.pop(context);
                                                                          return Navigator.of(context, rootNavigator: true)
                                                                              .pop();
                                                                        },
                                                                      );
                                                                      AlertDialog
                                                                          alert =
                                                                          AlertDialog(
                                                                        title: Text(
                                                                            "Warning!"),
                                                                        content:
                                                                            Text("No internet connection!"),
                                                                        actions: [
                                                                          okButton,
                                                                        ],
                                                                      );
                                                                      showDialog(
                                                                        context:
                                                                            context,
                                                                        builder:
                                                                            (BuildContext
                                                                                context) {
                                                                          return alert;
                                                                        },
                                                                      );
                                                                    } else {
                                                                      Fluttertoast.showToast(
                                                                          msg:
                                                                              "Successfull profile update!",
                                                                          toastLength: Toast
                                                                              .LENGTH_SHORT,
                                                                          gravity: ToastGravity
                                                                              .CENTER,
                                                                          timeInSecForIosWeb:
                                                                              1,
                                                                          backgroundColor: Colors
                                                                              .green,
                                                                          textColor: Colors
                                                                              .white,
                                                                          fontSize:
                                                                              16.0);
                                                                    }
                                                                  });
                                                                }
                                                              },
                                                              child: Align(
                                                                alignment:
                                                                    Alignment
                                                                        .center,
                                                                child: Text(
                                                                  '''Update Profile''',
                                                                  overflow:
                                                                      TextOverflow
                                                                          .visible,
                                                                  textAlign:
                                                                      TextAlign
                                                                          .center,
                                                                  style:
                                                                      TextStyle(
                                                                    height:
                                                                        1.1718750566012155,
                                                                    fontSize:
                                                                        29.485763549804688,
                                                                    fontFamily:
                                                                        'Work Sans',
                                                                    fontWeight:
                                                                        FontWeight
                                                                            .w700,
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            255,
                                                                            255,
                                                                            255),

                                                                    /* letterSpacing: -0.5897152709960938, */
                                                                  ),
                                                                ),
                                                              )),
                                                    ))
                                              ]),
                                        )),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 253.0,
                                    height: 57.0,
                                    child: TransformHelper.translate(
                                        x: 0.00,
                                        y: 380,
                                        z: 0,
                                        child: Container(
                                          width: 253.0,
                                          height: 57.0,
                                          child: Stack(
                                              fit: StackFit.expand,
                                              alignment: Alignment.center,
                                              overflow: Overflow.visible,
                                              children: [
                                                Positioned(
                                                  left: null,
                                                  top: null,
                                                  right: null,
                                                  bottom: null,
                                                  width: 253.0,
                                                  height: 57.0,
                                                  child:
                                                      GeneratedEllipse10Widget(),
                                                ),
                                                Positioned(
                                                    left: null,
                                                    top: null,
                                                    right: null,
                                                    bottom: null,
                                                    width: 253.97984313964844,
                                                    height: 41.727272033691406,
                                                    child: TransformHelper
                                                        .translate(
                                                      x: 0.49,
                                                      y: 0.14,
                                                      z: 0,
                                                      child:
                                                          FloatingActionButton(
                                                              backgroundColor:
                                                                  Colors
                                                                      .transparent,
                                                              elevation: 0,
                                                              onPressed:
                                                                  () async {
                                                                bloc
                                                                    .getLoggedUser()
                                                                    .then(
                                                                        (value) {
                                                                  bloc.deleteEntry(
                                                                      value.id);

                                                                  Fluttertoast.showToast(
                                                                      msg:
                                                                          "Successfull delete account!",
                                                                      toastLength:
                                                                          Toast
                                                                              .LENGTH_SHORT,
                                                                      gravity: ToastGravity
                                                                          .CENTER,
                                                                      timeInSecForIosWeb:
                                                                          1,
                                                                      backgroundColor:
                                                                          Colors
                                                                              .green,
                                                                      textColor:
                                                                          Colors
                                                                              .white,
                                                                      fontSize:
                                                                          16.0);

                                                                  Navigator.of(
                                                                          context)
                                                                      .pushNamed(
                                                                          '/');
                                                                });
                                                              },
                                                              child: Align(
                                                                alignment:
                                                                    Alignment
                                                                        .center,
                                                                child: Text(
                                                                  '''Delete Account''',
                                                                  overflow:
                                                                      TextOverflow
                                                                          .visible,
                                                                  textAlign:
                                                                      TextAlign
                                                                          .center,
                                                                  style:
                                                                      TextStyle(
                                                                    height:
                                                                        1.1718750566012155,
                                                                    fontSize:
                                                                        29.485763549804688,
                                                                    fontFamily:
                                                                        'Work Sans',
                                                                    fontWeight:
                                                                        FontWeight
                                                                            .w700,
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            255,
                                                                            255,
                                                                            255),

                                                                    /* letterSpacing: -0.5897152709960938, */
                                                                  ),
                                                                ),
                                                              )),
                                                    ))
                                              ]),
                                        )),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: null,
                                    bottom: null,
                                    width: 129.0,
                                    height: 116.0,
                                    child: TransformHelper.translate(
                                        x: -3.00,
                                        y: -410,
                                        z: 0,
                                        child: GeneratedGroup13Widget()),
                                  )
                                ])))
                  ])),
            );
          }),
        )));
  }
}
